record:
  type: ApplicationRecord
  version: 0.0.2
  repository_ref: 351db16336eacc3e1f9119ceb8d1282b8e27a27e
  repository: ["https://git.vdb.to/cerc-io/snowballtools-base"]
  app_type: webapp
  name: deploy-frontend
  app_version: 1.0.0
