record:
  type: ApplicationRecord
  version: 0.0.25
  repository_ref: 94a9bf88a9cf8442ffd37ad924cf9a590af69431
  repository: ["https://git.vdb.to/cerc-io/snowballtools-base"]
  app_type: webapp
  name: snowballtools-base-frontend
  app_version: 0.1.7
