[server]
  host = "127.0.0.1"
  port = 8000
  gqlPath = "/graphql"

[database]
  dbPath = "db/snowball"

[gitHub]
  webhookUrl = ""
  [gitHub.oAuth]
    clientId = ""
    clientSecret = ""

[registryConfig]
  restEndpoint = "http://localhost:1317"
  gqlEndpoint = "http://localhost:9473/api"
  chainId = "laconic_9000-1"
  privateKey = ""
  bondId = ""
  [registryConfig.fee]
    amount = "200000"
    denom = "aphoton"
    gas = "550000"
