[server]
  host = "127.0.0.1"
  port = 8000
  gqlPath = "/graphql"
  [server.session]
    secret = "p4yfpkqnddkui2iw7t6hbhwq74lbqs7bhobvmfhrowoi"
    appOriginUrl = 'http://localhost:3000'
    trustProxy = false
    domain = "localhost"

[database]
  dbPath = "db/snowball"

[gitHub]
  webhookUrl = ""
  [gitHub.oAuth]
    clientId = ""
    clientSecret = ""

[registryConfig]
  fetchDeploymentRecordDelay = 5000
  restEndpoint = "http://localhost:1317"
  gqlEndpoint = "http://localhost:9473/api"
  chainId = "laconic_9000-1"
  privateKey = ""
  bondId = ""
  [registryConfig.fee]
    amount = "200000"
    denom = "aphoton"
    gas = "750000"

[misc]
  projectDomain = "apps.snowballtools.com"
