services:
  registry:
    rpcEndpoint: https://laconicd-sapo.laconic.com
    gqlEndpoint: https://laconicd-sapo.laconic.com/api
    userKey: 
    bondId: 
    chainId: laconic_9000-2
    gasPrice: 1alnt
