export default [
  {
    id: '1',
    name: 'Progressive Web App (PWA)',
    icon: 'pwa',
    gitHubRepoFullName: `${process.env.REACT_APP_GITHUB_PWA_TEMPLATE_REPO}`,
    giteaRepoFullName: `${process.env.REACT_APP_GITEA_PWA_TEMPLATE_REPO}`,
    isComingSoon: false,
  },
  {
    id: '2',
    name: 'Image Upload PWA',
    icon: 'pwa',
    gitHubRepoFullName: `${process.env.REACT_APP_GITHUB_IMAGE_UPLOAD_PWA_TEMPLATE_REPO}`,
    giteaRepoFullName: '',
    isComingSoon: false,
  },
  {
    id: '3',
    name: 'Kotlin',
    icon: 'kotlin',
    gitHubRepoFullName: '',
    giteaRepoFullName: '',
    isComingSoon: true,
  },
  {
    id: '4',
    name: 'React Native',
    icon: 'react-native',
    gitHubRepoFullName: '',
    giteaRepoFullName: '',
    isComingSoon: true,
  },
  {
    id: '5',
    name: 'Swift',
    icon: 'swift',
    gitHubRepoFullName: '',
    giteaRepoFullName: '',
    isComingSoon: true,
  },
];
