name: Test webapp deployment and undeployment flow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'
  pull_request:
    branches: '*'

jobs:
  test_app_deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Test webapp deployment
        run: ./packages/deployer/test/test-webapp-deployment-undeployment.sh
